[package]
name = "deepgram"
version = "0.2.1"
authors = ["Deepgram <developers@deepgram.com>"]
edition = "2021"
description = "Official Rust SDK for Deepgram's automated speech recognition APIs."
license = "MIT"
repository = "https://github.com/deepgram-devs/deepgram-rust-sdk"
keywords = ["deepgram", "asr", "transcription", "ai", "speech-to-text"]
categories = ["api-bindings", "multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO Investigate which of these dependencies can go behind features.
bytes = "1"
openssl-sys = "0.9.88"
futures = "0.3"
http = "0.2"
pin-project = "1"
reqwest = { version = "0.11.10", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }
tokio-util = { version = "0.7.1", features = ["codec", "io"] }
tungstenite = "0.17"
url = "2"
uuid = { version = "1", features = ["serde"] }

[dev-dependencies]
cpal = "0.13"
crossbeam = "0.8"
